// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather/WeatherAlertService.proto

package weather

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AlertRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertRequest) Reset()         { *m = AlertRequest{} }
func (m *AlertRequest) String() string { return proto.CompactTextString(m) }
func (*AlertRequest) ProtoMessage()    {}
func (*AlertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ff12f7f0493ada3, []int{0}
}

func (m *AlertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertRequest.Unmarshal(m, b)
}
func (m *AlertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertRequest.Marshal(b, m, deterministic)
}
func (m *AlertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertRequest.Merge(m, src)
}
func (m *AlertRequest) XXX_Size() int {
	return xxx_messageInfo_AlertRequest.Size(m)
}
func (m *AlertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertRequest proto.InternalMessageInfo

type AlertResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertResponse) Reset()         { *m = AlertResponse{} }
func (m *AlertResponse) String() string { return proto.CompactTextString(m) }
func (*AlertResponse) ProtoMessage()    {}
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ff12f7f0493ada3, []int{1}
}

func (m *AlertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertResponse.Unmarshal(m, b)
}
func (m *AlertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertResponse.Marshal(b, m, deterministic)
}
func (m *AlertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertResponse.Merge(m, src)
}
func (m *AlertResponse) XXX_Size() int {
	return xxx_messageInfo_AlertResponse.Size(m)
}
func (m *AlertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AlertResponse proto.InternalMessageInfo

func (m *AlertResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*AlertRequest)(nil), "weather.AlertRequest")
	proto.RegisterType((*AlertResponse)(nil), "weather.AlertResponse")
}

func init() { proto.RegisterFile("weather/WeatherAlertService.proto", fileDescriptor_9ff12f7f0493ada3) }

var fileDescriptor_9ff12f7f0493ada3 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x4f, 0x4d, 0x2c,
	0xc9, 0x48, 0x2d, 0xd2, 0x0f, 0x87, 0xd0, 0x8e, 0x39, 0xa9, 0x45, 0x25, 0xc1, 0xa9, 0x45, 0x65,
	0x99, 0xc9, 0xa9, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0x25, 0x4a, 0x7c, 0x5c,
	0x3c, 0x60, 0xe9, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x65, 0x2e, 0x5e, 0x28, 0xbf,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x88, 0x8b, 0xa5, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x36, 0x8a, 0xe7, 0x12, 0xc6, 0x62, 0xb4, 0x90, 0x07, 0x97,
	0xb8, 0x7b, 0x6a, 0x89, 0x73, 0x69, 0x51, 0x51, 0x6a, 0x5e, 0x89, 0x73, 0x51, 0x66, 0x49, 0x66,
	0x72, 0x62, 0x0e, 0x58, 0x85, 0x90, 0xa8, 0x1e, 0xd4, 0x42, 0x3d, 0x64, 0xdb, 0xa4, 0xc4, 0xd0,
	0x85, 0x21, 0x96, 0x26, 0xb1, 0x81, 0x5d, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x62, 0xa3,
	0x97, 0x54, 0xca, 0x00, 0x00, 0x00,
}
